name = "dwell-birthday-calendar"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.development]
name = "dwell-birthday-calendar-dev"
[[env.development.kv_namespaces]]
binding = "BIRTHDAY_KV"
id = "83f5ade22d674bb38f857b367de5c7a7"
preview_id = "83f5ade22d674bb38f857b367de5c7a7"

[env.production]
name = "dwell-birthday-calendar-prod"
[[env.production.kv_namespaces]]
binding = "BIRTHDAY_KV"
id = "83f5ade22d674bb38f857b367de5c7a7"

# Environment variables (will be set via wrangler secret put)
# [vars]
# SLACK_SIGNING_SECRET = "TBD"
# SLACK_CLIENT_ID = "TBD"
# SLACK_CLIENT_SECRET = "TBD"
# ADMIN_PASSWORD = "TBD"