name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_ENV: production

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run full CI pipeline
        run: |
          npm run lint
          npm run type-check
          npm run test
          npm run build
          
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env production
          
      - name: Notify deployment success
        if: success()
        run: |
          echo "🚀 Deployment to production completed successfully!"
          echo "App URL: https://birthday.angiesplantdiary.com"
          
      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Deployment to production failed!"
          echo "Please check the logs for more details."