name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - production

env:
  NODE_ENV: production

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run full CI pipeline
        run: |
          npm run lint
          npm run type-check
          npm run test
          npm run build
          
      - name: Install Wrangler
        run: npm install -g wrangler
        
      - name: Deploy to Cloudflare Workers
        run: wrangler deploy --env ${{ github.event.inputs.environment }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      - name: Notify deployment success
        if: success()
        run: |
          if [ "${{ github.event.inputs.environment }}" = "production" ]; then
            echo "🚀 Deployment to production completed successfully!"
            echo "App URL: https://birthday.angiesplantdiary.com"
          else
            echo "🚀 Deployment to development completed successfully!"
            echo "App URL: https://dev-birthday.angiesplantdiary.com"
          fi
          
      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Deployment to ${{ github.event.inputs.environment }} failed!"
          echo "Please check the logs for more details."